### ISSUE TITLE
Improve consistency between wiki examples

### ISSUE THREAD

**Issue by jparreira** [NVentimiglia/Realtime-Unity3d#2]
Referring to: **https://github.com/NVentimiglia/Realtime-Unity3d/wiki/2)-Quickstart#send**

The subscribe example uses `Channel` as a variable while the send example uses it as a literal string.

**Comment by NVentimiglia** [comment]
Made everything a string literal, is that right ?

**Comment by jparreira** [comment]
Sure, it's consistent this way. Thanks for the update.
